### ISSUE TITLE
Write guidance on how to use NHS App frontend in production 

### ISSUE THREAD

**Issue by anna-rigo** [nhsuk/nhsapp-frontend#144]
### Description

The NHS App Design System team will write a guidance on how to the NHS App frontend in production and add it to their microsite. 

### Related documentation

NHS App microsite [link](https://design-system.nhsapp.service.nhs.uk/).

### Evidence (where applicable)

Supported by user needs uncovered through remote interviews - ideation sessions Mural link can be found [here](https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1719240510610/394e6c2b0bbad36d03fa5d19ec92ca58aa6d003c?wid=0-1722349407943&outline=open).

**Comment by davidhunter08** [comment]
The MoJ Design System has 4 guidance pages:

1. [Production](https://design-patterns.service.justice.gov.uk/get-started/production/)
2. [Installing with NPM](https://design-patterns.service.justice.gov.uk/get-started/installing-with-npm/)
3. [Setting up JavaScript](https://design-patterns.service.justice.gov.uk/get-started/setting-up-javascript/)
4. [Installing compiled files](https://design-patterns.service.justice.gov.uk/get-started/installing-compiled/)

**Comment by davidhunter08** [comment]
https://github.com/nhsuk/nhsapp-frontend/pull/150
