### ISSUE TITLE
Add a 'Get started' page

### ISSUE THREAD

**Issue by anna-rigo** [nhsuk/nhsapp-frontend#145]
### Description

The NHS App Design System team is looking to add a 'Get started' page to their microsite which would inform users of the microsite's purpose, resources, and how to use it. 

### Related documentation

NHS App microsite [link](https://design-system.nhsapp.service.nhs.uk/).

### Evidence (where applicable)

Supported by user needs uncovered through remote interviews - ideation sessions Mural link can be found [here](https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1719240510610/394e6c2b0bbad36d03fa5d19ec92ca58aa6d003c?wid=0-1722349407943&outline=open).

**Comment by davidhunter08** [comment]
https://github.com/nhsuk/nhsapp-frontend/pull/150
