### ISSUE TITLE
Add a 'How to contribute' section

### ISSUE THREAD

**Issue by anna-rigo** [nhsuk/nhsapp-frontend#146]
### Description

The NHS App Design System team is looking to add a 'How to contribute' section to their microsite to give more information about contributions and encourage users to feedback their insights, experiences and ideas to our team. 

### Related documentation

NHS App microsite [link](https://design-system.nhsapp.service.nhs.uk/) 

### Evidence (where applicable)

Supported by user needs uncovered through remote interviews - ideation sessions Mural link can be found [here](https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1719240510610/394e6c2b0bbad36d03fa5d19ec92ca58aa6d003c?wid=0-1722349407943&outline=open).

**Comment by Graham-Pembrey** [comment]
I've drafted an overview 'How to contribute' page, with an aim to cover the key messages in one place: https://docs.google.com/document/d/1XtU97SJ0TZOmgYnxJb8qbweEiy3xFn1LShRq19kE85c/edit?usp=sharing 

Feedback gratefully received. This could potentially be the first page of the section. These are the potential surrounding pages that have been suggested by the team:

- Backlog
- The team
- Roadmap
- How we work
- Upcoming components and patterns

**Comment by davidhunter08** [comment]
https://github.com/nhsuk/nhsapp-frontend/pull/150
