### ISSUE TITLE
Expander

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsapp-frontend#71]
## What

Expander used to hide and reveal more information on user interaction

![Image](https://github.com/nhsuk/nhsapp-frontend/assets/71393402/34a43f20-6da9-420c-afdb-950bf0ca8dad)

![Image](https://github.com/nhsuk/nhsapp-frontend/assets/71393402/6836dadd-a605-4c86-9c49-3ea3c252d73b)

### References
https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/29

**Comment by Tosin-Balogun** [comment]
This currently used by the prescriptions and medicines team to show service opening times

![Image](https://github.com/nhsuk/nhsapp-frontend/assets/71393402/2f701aff-747a-4c1f-9a32-a3bc81c81011)

**Comment by davidhunter08** [comment]
Closing as component exists in NHS design system
