### ISSUE TITLE
Inset text

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsapp-frontend#72]
## What
Inset text is used to make content stand out even if the user does not read the whole page

![Image](https://github.com/nhsuk/nhsapp-frontend/assets/71393402/2c203128-f84c-4f32-b195-27c259366c49)

### References
https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/18

**Comment by Tosin-Balogun** [comment]
This is used on prescriptions and medicines

![Image](https://github.com/nhsuk/nhsapp-frontend/assets/71393402/efa1fd71-a338-40e8-9584-5f46b92dba3c)



![Image](https://github.com/nhsuk/nhsapp-frontend/assets/71393402/b710f9ab-cbf0-4328-9344-5c4e6c1f447d)

**Comment by davidhunter08** [comment]
Closing as component exists in NHS design system
